"""message

Revision ID: 4829eff5c64e
Revises: 421ca9d2c13b
Create Date: 2025-09-21 14:35:09.645445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4829eff5c64e'
down_revision = '421ca9d2c13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
